	<script type="text/javascript" src="/core/js/jquery.js"></script>
	<script type="text/javascript" src="/core/js/jquery-ui.js"></script>

	<script type="text/javascript" src="/core/js/tg/core.js"></script>
	<script type="text/javascript" src="/core/js/tg/inpageform.js"></script>
	<script type="text/javascript" src="/core/js/jquery.inherit.js"></script>
	<script type="text/javascript" src="/core/js/jquery.contextmenu.r2.js"></script>
	<script type="text/javascript" src="/core/js/swfupload/swfupload.js"></script>
	<script type="text/javascript" src="/core/js/tg/core.js"></script>
	
	<script type="text/javascript" src="/core/js/tg/cms.form.js"></script>
	<script type="text/javascript" src="/core/js/tg/cms.form.field.js"></script>
	<script type="text/javascript" src="/core/js/tg/cms.form.field.group.js"></script>
	<script type="text/javascript" src="/core/js/tg/cms.form.field.groupoption.js"></script>
	<script type="text/javascript" src="/core/js/tg/cms.form.field.text.js"></script>
	<script type="text/javascript" src="/core/js/tg/cms.form.field.file.js"></script>
	<script type="text/javascript" src="/core/js/tg/cms.form.field.html.js"></script>
	<script type="text/javascript" src="/core/js/tg/cms.form.field.date.js"></script>
	<script type="text/javascript" src="/core/js/tg/cms.page.js"></script>
	<script type="text/javascript" src="/core/js/tg/fileupload.js"></script>
	<script type="text/javascript" src="/core/js/tiny_mce/jquery.tinymce.js"></script>
	<script type="text/javascript" src="/core/js/filebrowser.js"></script>
	
	<link href="/core/css/cms.css" media="screen" rel="stylesheet" type="text/css" />

	<?php echo $this->form?>