
<div id="footer">
	<div id="footer_inside">
		<div id="footer-share"><a href="#" id="shareThisButton"><img src="/images/share_btn_footer.png" width="104" height="28" alt="Share This" /></a></div>
		<div id="footer-menu">		
			<div id="footer-menu-nav">
				<ul class="footer_nav">
				<li><a href="http://www.retire.com.au" target="_blank">retire.com.au</a></li> 
				<li> . </li> 
				<li>*<a href="/info/tandc" class="popup">Terms and Conditions</a></li> 
				<li> . </li> 
				<li><a href="/info/enquiry" class="popup">Contact us</a></li> 
				</ul>
			</div>			
		</div>
		
		<div id="footer-menu-copy">  
			Copyright &copy;   
			<script type="text/javascript">
			now=new Date();
			year=now.getFullYear();
			</script><script type="text/javascript">
			document.write(year);
			</script> 
			Stockland Corporation Limited ACN 000 181 733
		</div>	
	</div>
</div><!--footer_inside Goes Here-->  

</div><!--Content for  id "footer" Goes Here-->