
    <?php echo $this->headMeta(); ?> 

	<meta property="og:url" content="www.springintoretirement.com.au.com.au" />
	<meta property="og:image" content="http://staging.springintoretirement.com.au/images/sharethis_image_thumb.jpg" />
	<meta property="og:description" content="Spring into retirement with $30,000 cash back on every available home" />
	<meta property="og:site_name" content="Spring into retirement" />

    <?php echo $this->headTitle(); ?> 
    
	<script src="/core/js/jquery.js" type="text/javascript"></script>
	<script src="/core/js/tg/core.js" type="text/javascript"></script>
	
    <?php echo $this->headStyle() ?>
    <?php echo $this->headLink() ?> 
    <?php echo $this->headScript() ?>
    
