<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->partial('_partials/html_head.phtml')?>

</head>

<body>
<div id="container">
    <div id="header">Header</div>
    <div id="nav"><?php echo $this->siteNav()?></div>
        <div id="content">
        <?php echo $this->layout()->content; ?>
        </div>
    </div>
</div>
</body>
</html>