<script type="text/javascript" src="/core/js/tiny_mce/tiny_mce_popup.js"></script>

<script language="javascript" type="text/javascript">
var FileBrowserDialogue = {
    init : function () {
        // Here goes your code for setting your custom things onLoad.
    },
    mySubmit : function (URL) {
//        var URL = document.my_form.my_field.value;
        var win = tinyMCEPopup.getWindowArg("window");

        // insert information now
        win.document.getElementById(tinyMCEPopup.getWindowArg("input")).value = URL;

        // are we an image browser
        if (typeof(win.ImageDialog) != "undefined")
        {
            // we are, so update image dimensions and preview if necessary
            if (win.ImageDialog.getImageData) win.ImageDialog.getImageData();
            if (win.ImageDialog.showPreviewImage) win.ImageDialog.showPreviewImage(URL);
        }

        // close popup window
        tinyMCEPopup.close();
    }
}
tinyMCEPopup.onInit.add(FileBrowserDialogue.init, FileBrowserDialogue);

function setUrl (url)
{
	FileBrowserDialogue.mySubmit(url);
}
</script>
<p><a href="/admin/file-browser/?type=file">Files</a> | <a href="/admin/file-browser/?type=pages">Pages</a></p>

<?php 
if ($this->files) {
	foreach ($this->files as $file) {
?>
<a href="#" onclick="setUrl('<?php echo $file->getUrl() ?>')"><?php echo $file->name?></a><br />
<?php 
	}
}
if ($this->page) {
	pages ($this->page);	
}


function pages ($page)
{
?>
<a href="#" onclick="setUrl('<?php echo $page->url ?>')"><?php echo $page->title?></a><br />
<?php 
	foreach ($page->Pages as $subpage) {
		pages ($subpage);
	}
}
?>