<link href="/core/js/valums/fileuploader.css" rel="stylesheet" type="text/css">	
<script src="/core/js/valums/fileuploader.js" type="text/javascript"></script>
<div id="file-uploader" style="float:right;"></div>
<div class="pageContent" id='content-div' style="width:100%"></div>
<script type="text/javascript">
Ext.onReady(function() {	
	createUploader ();
	c("!")
});

function createUploader(){
	var uploader = new qq.FileUploader({
		element: document.getElementById('file-uploader'),
		action: '/admin/file-upload-valums',
		onComplete: function (var1, var2, var3) {
			c (var1+":"+var2+":"+var3);
			return true;
		},
		debug: true
	});
}
</script>
