<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Get Reading!</title>
<style type="text/css">
<!--
-->
</style>
<link href="css/default.css" rel="stylesheet" type="text/css" />
</head>

<body>

<div id="red-border">
<div id="gray-border">
<div id="container">
<?php echo $this->layout()->content; ?>
</div>
</div>
</div>
</body>
</html>