<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head> 
	<?php echo $this->headMeta(); ?> 
	<?php echo $this->headTitle(); ?>
	
	<?php echo $this->headCore(array('includeJquery'=>true)); ?>
    <link href="/themes/backend/css/global.css" rel="stylesheet" type="text/css" />
	<script src="/themes/backend/js/admin.js" type="text/javascript"></script>
	
	<?php echo $this->headStyle() ?>
	<?php echo $this->headLink() ?> 
	<?php echo $this->headScript() ?>
</head> 
<body> 
    <div id="container">
       <div id="header">
        </div>
        <div id="nav">
	        <div id="navLogo"></div>
				<?php echo $this->siteNav('/admin', array ('pruneRestricted'=>true))?>
        </div>
        <div id="contentContainer">
				   	<?php echo $this->layout()->content; ?>
        </div>
        <div id="footer">
        	<div id="user">
				<?php if ($this->currentUser){?>
				<?php echo $this->currentUser->name?> | <a href="/login/logout">Sign out</a>
				<?php } else {?>
				<a href="/register" class="green">Register</a> | <a href="/login">Log In</a>
				<?php }?>
            </div>
        </div>
    </div>
</body> 
</html>