<table class="list" width="100%" cellspacing="0">
	<thead>
		<tr>
		<th>Edit - <?php echo $this->siteBreadcrumb ( 
		array(
		'urlPre'=>'/admin/site/page-edit?page=',
		'includeRoot'=>true,
		'seperator'=>'&nbsp;/&nbsp;',
		'aNormalClass'=>'inPageForm'		
		), $this->Page)?></th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td>
		<?php echo $this->message?>
		<?php echo $this->form?>
		</td>
	</tr>
	</tbody>
</table>	
