<table class="list" width="100%" cellspacing="0">
<thead>
		<tr>
		<th>Add - <?php echo $this->siteBreadcrumb ( 
		array(
		'urlPre'=>'/admin/site/page-edit?page=',
		'includeRoot'=>true,
		'seperator'=>'&nbsp;/&nbsp;',
		'aNormalClass'=>'inPageForm'		
		), $this->Parent)?> / Untitled</th>
	</tr>
</thead>
<tbody>
	<tr>
		<td>
		<?php echo $this->message?>
		<?php echo $this->form?>
		</td>
	</tr>
</tbody>
</table>

<?php if ($this->updatePageList) { ?>
<script type="text/javascript" language="javascript">
$(document).ready(function() {
	$('#PmPagesPageList').load("/admin/site/page-list");
});
</script>
<?php } ?>