<table class="list" width="100%" cellspacing="0">
	<thead>
		<tr>
			<th>Assigned Roles</th>
			<th></th>
		</tr>
	</thead>
<tbody>
<?php 
$userRoleIds = array ();
foreach ($this->userRoles as $role) {
	$userRoleIds[] = $role->id;	
	?>
<tr>
	<td><?php echo( $role->name)?></td>
	<td><a href="/admin/user/user-roles?user=<?php echo $this->user->id?>&role=<?php echo $role->id?>&do=DELETE" class="control delete inPageForm" title="Delete">Delete</a></td>
</tr>
<?php }?>
</tbody>
</table>
<p> </p>

<table class="list" width="100%" cellspacing="0">
	<thead>
		<tr>
			<th>Available Roles</th>
			<th></th>
		</tr>
	</thead>
<tbody>
<?php foreach ($this->roles as $role) {
	if (!in_array($role->id,$userRoleIds)){?>
<tr>
	<td><?php echo ( $role->name)?></td>
	<td><a href="/admin/user/user-roles?user=<?php echo $this->user->id?>&role=<?php echo $role->id?>&do=ADD" class="control add inPageForm" title="Add">Add</a></td>
</tr>
<?php }
}?>
</tbody>
</table>