
    <?php echo $this->headMeta(); ?> 

	<meta property="og:url" content="www.springintoretirement.com.au.com.au" />
	<meta property="og:image" content="http://staging.springintoretirement.com.au/images/sharethis_image_thumb.jpg" />
	<meta property="og:description" content="Spring into retirement with $30,000 cash back on every available home" />
	<meta property="og:site_name" content="Spring into retirement" />

    <?php echo $this->headTitle(); ?> 
    
	<script src="/js/jquery.js" type="text/javascript"></script>
	<script src="/core/js/tg/core.js" type="text/javascript"></script>
	<script src="/core/js/fancybox/jquery.fancybox-1.3.4.pack.js" type="text/javascript"></script>
	<script src="/js/global.js" type="text/javascript"></script>
	
    <?php echo $this->headStyle() ?>
    <?php echo $this->headLink() ?> 
    <?php echo $this->headScript() ?>
    
    <link href="/core/js/fancybox/jquery.fancybox-1.3.4.css" rel="stylesheet" type="text/css" />
	<link href="/css/default.css" rel="stylesheet" type="text/css" />	
		
		
	<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
	<script type="text/javascript">
	stLight.options({
	publisher:'1c46526a-0742-43f9-9981-f67856085ae5'
	});
	</script>        

		
	<!-- Start: Google Analytics --->
	<script type="text/javascript">
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-5552582-1']);
	_gaq.push(['_setDomainName', '.springintoretirement.com.au']);
	_gaq.push(['_setAllowHash', false]);
	_gaq.push(['_setAllowLinker', true]);
	_gaq.push(['_trackPageview']);
	(function() {var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();
	</script>
	
	<script type="text/javascript">
	function xDomainLink(destination) {
	var currentDomain = location.hostname; // Gets the hostname for the current site
	_gaq.push(['tracker._trackEvent', currentDomain, destination]); // Sends an event to Analytics
	setTimeout("_gaq.push(['tracker._link', destination]);", 100); // Delays the link to the new location
	}
	</script>
	
	<!-- End: Google Analytics Code -->
		