<?php echo $this->doctype()?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headMeta(); ?>

	<?php echo $this->headStyle() ?>
	<?php echo $this->headLink() ?>
	<?php echo $this->headScript() ?>

    <link href="<?php echo $this->pathTheme()?>/css/style.css" rel="Stylesheet" type="text/css" />
	<script src="<?php echo $this->pathTheme()?>/js/script.js" type="text/javascript"></script>
</head>

<body>
<div id="container">
    <div id="header">Header</div>
    <div id="nav">Nav</div>
        <div id="content">
        <?php echo $this->layout()->content; ?>
        </div>
    </div>
</div>
</body>
</html>